sudo: required
services:
  - docker
script:
  - docker build -t practicacloud .
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag practicacloud $DOCKER_USER/practicacloud
  - docker push $DOCKER_USER/practicacloud
